version: '3.3'

services:
  product-app-devl:
    build: .
    container_name: "product-app-devl"
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=devl"

  product-app-prod:
    build: .
    container_name: "product-app-prod"
    ports:
      - 9080:9080
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  product-db-devl:
    image: 'postgres:latest'
    restart: always
    container_name: product-db-devl
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      POSTGRES_USER: product_app
      POSTGRES_PASSWORD: pass1
      MYSQL_DATABASE: product
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ${PWD}/product-data-devl/:/var/lib/postgresql

  product-db-prod:
    image: 'postgres:latest'
    restart: always
    container_name: product-db-prod
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      POSTGRES_USER: product_app
      POSTGRES_PASSWORD: pass1
      MYSQL_DATABASE: product
      POSTGRES_DB: productdb
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - ${PWD}/product-data-prod/:/var/lib/postgresql


volumes:
  product-data-devl:
  product-data-prod:
