version: '3.3'

services:
  product-db:
    image: 'postgres:latest'
    restart: always
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      POSTGRES_USER: product_app
      POSTGRES_PASSWORD: pass1
      MYSQL_DATABASE: product
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ${PWD}/product-data/:/var/lib/postgresql


volumes:
  product-data:
