server:
  port: 9080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/productdb
    username: product_app
    password: pass1
    driverClassName: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
