spring:
  profiles:
    default: devl
  main:
    lazy-initialization: true
  application:
    name: REST Services Application
    version: ${version}
  config:
    import:
      - autoconfigure-exclusions.yml


token:
  secret: some-secret-and-it-should-be-longer

