spring:
  main:
    lazy-initialization: true
  application:
    name: REST Services Application
    version: ${version}
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


token:
  secret: some-secret-and-it-should-be-longer

