spring:
  main:
    lazy-initialization: true
  application:
    name: client-app
    version: ${version}

server:
  port: 8090

## These should come from a vault
api:
  product:
    endpoint: http://localhost:8080
  auth:
    endpoint: http://localhost:8080
    user: user
    pass: pass1

