openapi: 3.1.0
info:
  title: Apply Default Global SecurityScheme in springdoc-openapi
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
security:
- bearerAuth: []
paths:
  /products/v1:
    get:
      tags:
      - Products
      operationId: getProducts
      responses:
        "404":
          description: No products found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Unable to process the request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    post:
      tags:
      - Products
      operationId: addProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      responses:
        "400":
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Unable to save the product.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
  /login:
    post:
      tags:
      - Authentication
      operationId: authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRequest"
        required: true
      responses:
        "200":
          description: api_key to be used in the secured-ping endpoint
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "401":
          description: Unauthorized request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security: []
  /products/v1/{id}:
    get:
      tags:
      - Products
      operationId: getProductById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: No product found matching the id.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Unable to process the request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
          minLength: 1
        price:
          type: number
          format: double
        createdDate:
          type: string
          format: date-time
      required:
      - title
    ErrorResponse:
      type: object
      properties:
        errorMessage:
          type: string
        errorDetails:
          type: string
        exception:
          type: string
    TokenResponse:
      type: object
      properties:
        raw:
          type: string
    AuthRequest:
      type: object
      properties:
        userName:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
      required:
      - password
      - userName
  securitySchemes:
    bearerAuth:
      type: http
      scheme: Bearer
      bearerFormat: JWT
