/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.16.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.bhuyanp.restapp.client.api;

import io.github.bhuyanp.restapp.client.model.AuthRequest;
import io.github.bhuyanp.restapp.client.model.TokenResponse;
import jakarta.annotation.Generated;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.service.annotation.HttpExchange;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-10-31T06:19:25.366540-04:00[America/New_York]", comments = "Generator version: 7.16.0")
public interface AuthenticationApi {

    /**
     * POST /authenticate
     * Returns valid JWT token
     *
     * @param authRequest  (required)
     * @return Invalid request. (status code 400)
     *         or Failed to obtain the token. (status code 500)
     *         or OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/authenticate",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<TokenResponse> authenticate(
         @RequestBody AuthRequest authRequest
    );

}
